# Slicing com Numpy

In [1]:
# Importando o módulo numpy
import numpy as np

In [2]:
array1 = np.arange(5); array1

array([0, 1, 2, 3, 4])

In [8]:
array1[1]

1

In [7]:
array1[-1]

4

In [10]:
array2 = np.arange(0, 100, 7); array2

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [19]:
# Invertendo um array
array2[::-1]

array([98, 91, 84, 77, 70, 63, 56, 49, 42, 35, 28, 21, 14,  7,  0])

In [24]:
matrix1 = np.matrix([[1, 2, 3], [4, 5, 6]]); matrix1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [25]:
matrix2 = np.matrix([[1, 2, 3], [4, 5, 6]]); matrix2

matrix([[1, 2, 3],
        [4, 5, 6]])

In [32]:
matrix1 + matrix2

matrix([[ 2,  4,  6],
        [ 8, 10, 12]])

In [33]:
matrix1 - matrix2

matrix([[0, 0, 0],
        [0, 0, 0]])